version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3010:3010"
    environment:
      - NODE_ENV=development
      - ACCESS_TOKEN_SECRET=your_secret_key_here
      - PORT=3010
  frontend:
    build: ./frontend
    ports:
      - "5000:80"
    environment:
      - NODE_ENV=development
